name: face
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - click=8.3.0=pyh7428d3b_0
  - cmake=4.1.2=hdcbee5b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - dlib=19.24.2=py310h65af467_2
  - face_recognition=1.3.0=pyhd3deb0d_2
  - face_recognition_models=0.3.0=pyh9f0ad1d_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - mkl=2025.3.0=hac47afa_454
  - numpy=1.26.4=py310hf667824_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - pillow=12.0.0=py310hfb50504_0
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=h0e40799_1002
  - python=3.10.19=hc20f281_2_cpython
  - python_abi=3.10=8_cp310
  - setuptools=80.9.0=pyhff2d567_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_2
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tzdata==2025.2
prefix: C:\Users\Green\miniconda3\envs\face
